### ISSUE TITLE
No self-correcting mechanism in case of data update failure

### ISSUE THREAD

**Issue by dundejan** [opensanctions/yente#554]
Two days ago, my yente task running in AWS failed to update and index new data. I checked the AWS stats and logs and there was no indicator of lack of system memory or compute time. Yet, the data update failed so I guess it is connected with bad data transport from data.opensanctions.org. The image seems to have no self-correcting mechanism for those cases that could initiate the data update once again in case there are some bad data obtained from the OpenSanctions.

Is there any way how to automatically set correcting those problems or can it be possibly part of new yente release?

Thanks for all comments or help about it

**Comment by pudo** [comment]
Hello Jan! I do wonder if there's any error/warning message in the container logs that gives a clue as to what may have gone wrong? What we do is we run the re-index job quite often (ca. every 30 mins) so that one failure just delays the update a little bit (all the in-between runs will effectively be no-ops). Make sure to use Yente 4.0 with that. 

Regarding `data.opensanctions.org`: we have seen the occasional connection reset and other errors from that. However, it's using Google Cloud CDN to serve out the data. I don't think anything we'd build at home would produce a lower error rate than pure Google infra, so not sure how to bring the rate down even further.
